### ISSUE TITLE
Error when running npm install with 1.2.2

### ISSUE THREAD

**Issue by mh1622** [olavoparno/istanbul-badges-readme#15]
**Describe the bug**
```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/USER/PROJECT/node_modules/istanbul-badges-readme/lib/index.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/USER/PROJECT/node_modules/istanbul-badges-readme/lib/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**To Reproduce**
1. Change dependency version from 1.2.1 to 1.2.2
2. Run `npm install`

**Additional context**
1.2.1 works fine locally and in github actions. 1.2.2 fails in both environments.
Node v14.16.0
Npm 6.14.11

**Comment by olavoparno** [comment]
Hello @mh1622 thanks for the report. I will look into it as soon as possible, for now please do use the previous version :)

**Comment by venturalp** [comment]
I've made a pull request in an attempt to fix this bug #16

**Comment by venturalp** [comment]
@all-contributors please add @mh1622 for bug

**Comment by olavoparno** [comment]
@all-contributors please add @mh1622 for bug

**Comment by olavoparno** [comment]
@mh1622 thank you again for the issue. Could you please check version 1.3.0 and give us a feedback wether the problem is solved or not?

**Comment by mh1622** [comment]
This appears fixed now. Impressive turnaround time! :clap:

**Comment by dutchenkoOleg** [comment]
Faced with error today with 1.2.2+ version (((

- macOS Big Sur
- node 16.0.0
- npm 7.10.0

1.2.0 version works fine

**Comment by olavoparno** [comment]
> Faced with this error today
> trying 1.2.2+ version (((
> 
> * macOS Big Sur
> * node 16.0.0
> * npm 7.10.0
> 
> 1.2.0 version works fine

Hello, @dutchenkoOleg , thanks for the issue. Reopening for further investigation.

**Comment by olavoparno** [comment]
We are deeply sorry the inconvenience and after a thorough troubleshooting we have finally come to a solution.

Please do check it with version 1.3.4 and if the problem is either solved or remaining, be so kind and reply us.

Thank you for using the library.

@all-contributors please add @dutchenkoOleg for bug

**Comment by dutchenkoOleg** [comment]
Sorry for my late. I tested - it works fine! Thanks!
