### ISSUE TITLE
fails to generate badge for 0% coverage

### ISSUE THREAD

**Issue by engineervix** [olavoparno/istanbul-badges-readme#2]
First of all, I'd like to thank you for this excellent package, this is absolutely great! Everything seems to work just fine, except I've noticed that if coverage is 0%, the badge isn't generated and hence substitution doesn't take place. For example, in my case, I had the following results:

```
=============================== Coverage summary ===============================
Statements   : 6.25% ( 1/16 )
Branches     : 0% ( 0/4 )
Functions    : 20% ( 1/5 )
Lines        : 7.14% ( 1/14 )
================================================================================
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        6.294s
Ran all test suites.
```
This resulted in

| Statements                | Functions                | Lines                | Branches                |
| ------------------------- | ------------------------ | -------------------- | ----------------------- |
| ![Statements](https://img.shields.io/badge/Coverage-6.25%25-red.svg) | ![Functions](https://img.shields.io/badge/Coverage-20%25-red.svg) | ![Lines](https://img.shields.io/badge/Coverage-7.14%25-red.svg) | ![Branches](#branches#) |

Thanks

**Comment by engineervix** [comment]
It seems this is also true for 100% coverage! Again, I experienced this on the coverage for **Branches**

**Comment by olavoparno** [comment]
Hey, first of all, sorry for the delay!

Thank you for the detailed explanation. I will look into it!

**Comment by olavoparno** [comment]
Hello again, mister @engineervix, could you please give another try using version 1.0.6?

https://github.com/olavoparno/istanbul-badges-readme/releases/tag/v1.0.6
https://www.npmjs.com/package/istanbul-badges-readme/v/1.0.6

**Comment by olavoparno** [comment]
Adds @engineervix as a contributor for bug reporting

**Comment by olavoparno** [comment]
@all-contributors please add @engineervix for bug reporting.

**Comment by engineervix** [comment]
> Hello again, mister @engineervix, could you please give another try using version 1.0.6?
> 
> https://github.com/olavoparno/istanbul-badges-readme/releases/tag/v1.0.6
> https://www.npmjs.com/package/istanbul-badges-readme/v/1.0.6

Hey @olavoparno, thank you so much for looking into this, and for adding me to the list of contributors! I can confirm that v1.0.6 fixes the problem! :smiley: :raised_hands: Muito obrigado!
