### ISSUE TITLE
Option to use Alternative Titles as Badge Titles

### ISSUE THREAD

**Issue by CREEATION** [olavoparno/istanbul-badges-readme#33]
As I don't really want to use the table layout but still need the context on which badge is which, using the already present `alt` attribute values (e.g. `Statements`, `Branches`, etc.) as titles for the badges (instead of `Coverage` for every badge) would be neat. 🐢

**Comment by olavoparno** [comment]
Hello, @CREEATION thanks for the issue! **We will definitely look into** it and I think you are right. This should come as default, indeed. We may also create a way of making it fully customizable as well.

**Comment by olavoparno** [comment]
@CREEATION is this what you mean? Disregard it being in a table though, see the badges naming.

![image](https://user-images.githubusercontent.com/7513162/121037449-d7cc4b80-c785-11eb-9c90-f0ed1d7d1943.png)

**Comment by CREEATION** [comment]
Hey, that was quick!
By "alt" I meant the literal "alt" attribute from the markdown.

e.g. here it's "**F**_unctions_" (alt), not "**f**_unctions_" (hashKey):
```
![Functions](#functions#)
   ^ this | not this ^
```
This way, I'd imagine, it's customizable very easily by just changing the markdown.

**Comment by olavoparno** [comment]
Oh, I think the library is not ready to work as you suggested :( what do you think of these proposed changes? Do they work for you? https://github.com/olavoparno/istanbul-badges-readme/pull/34/files

We decided to postpone a customization where one would be able to change each hashKey as desired.

**Comment by CREEATION** [comment]
Sure, that's already looking good for me in contrast to all badges being "Coverage".
Is it possible to add a CLI argument so people who want the previous behaviour don't get angry because of me opening this issue? 😄

Thanks for the quick responses! 🐢

**Comment by olavoparno** [comment]
Yeah, it passed through our minds this idea of `istanbul-badges-readme --functions="funciones" --statements="declaraciones"` of sorts but you may be right. Are you in a hurry? We will come back to you as soon as possible. Thank you again for the issue and the prompt response.

**Comment by CREEATION** [comment]
Nah, it's not urgent at all. Take your time, stretch and stay healthy! :) 💚

**Comment by olavoparno** [comment]
@CREEATION please do check for version 1.4.0.

https://github.com/olavoparno/istanbul-badges-readme#usage

You can now rename alts (badge labels) as you wish or just let it assume its corresponding hashes automatically.
```
npm run istanbul-badges-readme --functionsLabel='Mis funciones!'
```

**Comment by olavoparno** [comment]
@all-contributors please add @CREEATION for ideas :) thank you
