### ISSUE TITLE
Ability to add logo argument when calling the package

### ISSUE THREAD

**Issue by David-Mimnagh** [olavoparno/istanbul-badges-readme#55]
**Is your feature request related to a problem? Please describe.**
Nope, using it for jest coverage badges and would just like to add the Jest logo in

**Describe the solution you'd like**
Adding the jest logo into the resulting badge, so it appears like so:
![image](https://user-images.githubusercontent.com/10092258/142223867-a8351550-bc60-4717-9544-955712574afa.png)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by olavoparno** [comment]
Hello, @David-Mimnagh thanks for the issue. We will definitely look into it! It will be amazing, indeed :)

Thank you and as soon as possible, I will give an update here.

**Comment by olavoparno** [comment]
@all-contributors please add @David-Mimnagh for ideas!

**Comment by olavoparno** [comment]
@David-Mimnagh could you please try out the version 1.7.0? https://www.npmjs.com/package/istanbul-badges-readme/v/1.7.0

**Comment by David-Mimnagh** [comment]
@olavoparno Works great! 
Thank you very much for adding this so quickly!

**Comment by olavoparno** [comment]
@David-Mimnagh thank you for the idea, it really is awesome and thanks for the prompt reply on testing the feature! Have a nice day!
