### ISSUE TITLE
feature request: exit with non-zero code upon validation errors

### ISSUE THREAD

**Issue by micalevisk** [olavoparno/istanbul-badges-readme#57]
**Is your feature request related to a problem? Please describe.**

Make the CLI exit with non-zero code if validation fails

Current behavior:

```
$ istanbul-badges-readme
Info: 0. Istanbul Badges Readme process started
Info: 1. Config check process started
- Readme file exists... ✔️.
Error: Coverage file does not exist in ./coverage/coverage-summary.json
Error: Please refer to the documentation
Error: https://github.com/olavoparno/istanbul-badges-readme/blob/master/README.md
Info: 0. Istanbul Badges Readme process finished
Done in 0.17s.
$ echo $?
0
```

Exiting with 0 prevent other tools (like GitHub Actions) to detect any validation errors of `istanbul-badges-readme` easily

**Describe the solution you'd like**

adding `process.exitCode = 1;` below will do the trick work but I'm pretty sure it will be a breaking change as some users could be relying on istanbul-badges-readme success exit code

https://github.com/olavoparno/istanbul-badges-readme/blob/805ab2e19931201fb80a949d1c9693ea29aac00d/src/factory.ts#L20-L24

thus, to avoid breaking changes, this feat could be optional and enabled via `--exit-code` flag, like [`git-diff` do](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---exit-code)

**Describe alternatives you've considered**

In my use case, the coverage directory might not exists and I need to report this as an error. I'm doing the following:

```bash
$ [ -d './coverage' ] && istanbul-badges-readme || exit 1
```

but I think it would be cool if `istanbul-badges-readme` abstracts this for us :)

**Comment by olavoparno** [comment]
Hello @micalevisk thanks for opening the issue. Yeah, I think it was a bad design decision, indeed, I think I forgot to throw the error after logging them, so now we have to deal this behavior haha

I will look into your suggestion! Thank you once again :)

**Comment by olavoparno** [comment]
@micalevisk hello again, sir, I am not having lots of spare time right now, would you mind opening a PR? If not, it's ok, I will try to do ASAP.

**Comment by micalevisk** [comment]
@olavoparno sure. Should I add `--exit-code` optional flag?

**Comment by olavoparno** [comment]
Yes, I think this is fine. If there's an explanation in the docs I think people will understand :) thank you, really.

**Comment by micalevisk** [comment]
btw I saw that other flags are following camel case then I've chose `--exitCode` instead :smile:

**Comment by olavoparno** [comment]
@micalevisk hello again! Sorry for the dalay, I was caught up with other things :( oh man, I took advantage of your WIP commit and I have already commited to the develop branch a version of exitCode. Sorry for your work, but I think it accomplishes the same thing as I think I got your idea.

**Comment by olavoparno** [comment]
@all-contributors please add @micalevisk for idea, code, bug

**Comment by olavoparno** [comment]
Please do take a look at version 1.8.0 https://www.npmjs.com/package/istanbul-badges-readme/v/1.8.0

Once again, thanks for the patience, mister @micalevisk

**Comment by myknbani** [comment]
I'm not sure if I'm using the flag correctly (or understood it correctly), but it always fails:

```
> istanbul-badges-readme --logo='jest' "--ci" "--exitCode=1"

Istanbul Badges Readme process started
Config check process started
- Readme file exists... ✔️.
- Coverage file exists... ✔️.
- Coverage hashes exist... ✔️.
- Readme hashes exist... ✔️.
Config check process ended
Editor process started
- Getting readme hashes...
- Getting new readme data...
- Getting coverage badge url for statements...
- Writing new readme data...
Editor process ended
Istanbul Badges Readme process finished
Error: Process completed with exit code 1.
```

**Comment by micalevisk** [comment]
after running this, what's the output of `echo $?`?

**Comment by micalevisk** [comment]
nvm. You're right. I just tested. This is a bug

**Comment by olavoparno** [comment]
@myknbani and @micalevisk there is indeed a bug. Thank you @myknbani for testing it. @micalevisk do you want to open a PR fixing it or shall I do so? Thank you too for your support by the way, I really appreciate it :)

**Comment by myknbani** [comment]
Also digging through the source code, it seems to just obey `--exitCode=whatever` all the time :cold_sweat:
![Screenshot from 2021-12-07 10-18-28](https://user-images.githubusercontent.com/5841268/144954109-de6e3c19-e832-4d51-b8de-cc9ef6bff0a5.png)

**Comment by myknbani** [comment]
@micalevisk is fast :sweat_smile:

**Comment by olavoparno** [comment]
@could you guys test it again https://www.npmjs.com/package/istanbul-badges-readme/v/1.8.1?

Thank you both for the help as always.

**Comment by olavoparno** [comment]
@all-contributors please add @myknbani for bug

**Comment by micalevisk** [comment]
@olavoparno 

it is working as expected now. ty for the quick release!

**Comment by myknbani** [comment]
Works on my end too.  Thank you @olavoparno and @micalevisk :tada: :partying_face:
