### ISSUE TITLE
bug: getNewReadme fails on users with others process.argv items with 'ci' substring

### ISSUE THREAD

**Issue by leticiavna** [olavoparno/istanbul-badges-readme#70]
**Describe the bug**
Hi! I was trying to run the script with npm following the steps in the documentation. However, it was always failing in this part of the process:

![image](https://user-images.githubusercontent.com/28829955/173661140-17f9bb6d-4078-468d-9a72-a9e643882abf.png)

Since I'm not running with the ci flag or in a ci environment, i went into the codebase to search how was this error message thrown.  I found that the _getArgumentValue_ function searches a string with _indexOf_ only: 

https://github.com/olavoparno/istanbul-badges-readme/blob/eb418586322559b3a00f5cca9e73abda2edd9379/src/arguments.ts#L7-L12

The problem with this is that for users who have user names, or node path, or maybe any other line in the process.argv with the 'ci' substring, the `item.indexof(argName) >= 0` returns true: 

![image](https://user-images.githubusercontent.com/28829955/173662325-3eacda39-e143-4ad1-b771-77574bbc9581.png)

In my case, changing my user and nvm path worked.

**To Reproduce**
1. Change or have a username/node path with 'ci' substring
2. Try to run instanbul-badges-readme inside a repository
3. Check error after editor process

**Additional context**
I was unsure if this is a node version related problem, but trying to run with v14.18.1 or 16.15.1 didnt work. Happy to help tho! Will submit a PR soon!

**Comment by olavoparno** [comment]
@leticiavna first of all, thank you for opening this issue and the PR. Really appreciate it.
Please, could you check version 1.8.2 and see if it is fixed?

**Comment by leticiavna** [comment]
@olavoparno sure! everything is working now. thank you for the quick review! 🚀
