### ISSUE TITLE
very small correction about README

### ISSUE THREAD

**Issue by canbax** [olavoparno/istanbul-badges-readme#78]
I did run `npm run istanbul-badges-readme` after that readme says you can run `npm run istanbul-badges-readme` but I cannot. It says 

> npm ERR! Missing script: "istanbul-badges-readme"

This is a very small thing. Thanks for this great library!

**Comment by micalevisk** [comment]
You should use `npx` instead of `npm run`. Otherwise you should add a new script in your package.json called `istanbul-badges-readme`

That was missed in the docs

**Comment by olavoparno** [comment]
Thank you again, guys. Closing it. @all-contributors please add @canbax for doc
