### ISSUE TITLE
Not throwing an error on CI if badges are changed

### ISSUE THREAD

**Issue by supunTE** [olavoparno/istanbul-badges-readme#79]
**Describe the bug**
Not throwing error on CI with --ci argument but only log appear.

Following is my script
```"make-badges:ci": "npm run make-badges -- --ci"```

**To Reproduce**
1. Add --ci after the make badge script as described on https://github.com/olavoparno/istanbul-badges-readme/blob/develop/README.md#usage-as-a-part-of-your-ci 
2. Run script
4. Not throwing an error.

**Additional context**
![image](https://user-images.githubusercontent.com/33794760/207236461-46b1a483-440d-4199-8356-f56decd12e95.png)

**Comment by olavoparno** [comment]
@supunTE hey there, sorry for the delay answering this. First of all, thanks for opening this issue.

This is a mistake on the README, I am sorry. The default exitCode for the --ci option is 0 but if you need it to really throw, you could run like so:

`"make-badges:ci": "npm run make-badges -- --ci --exitCode=1"`

**Comment by olavoparno** [comment]
@all-contributors please add @supunTE for doc

**Comment by olavoparno** [comment]
https://github.com/all-contributors please add @supunTE for doc

**Comment by supunTE** [comment]
Well I think problem is solved now.

**Comment by olavoparno** [comment]
Thanks. Closing issue.
